"""empty message

Revision ID: b7fd0955fc8e
Revises: 6127985218e1
Create Date: 2022-08-18 11:26:10.359579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7fd0955fc8e'
down_revision = '6127985218e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    # ### end Alembic commands ###
